services:
  mongodb:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cars
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      #- ./init-car.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: "echo 'db.runCommand({ serverStatus: 1 }).ok' | mongosh --authenticationDatabase admin --host \
            mongodb -u root -p example --quiet | grep -q 1"
      interval: 10s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: 'mongodb://root:example@mongodb:27017/cars?authSource=admin'
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
    ports:
      - 5000:5000

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  mongo_data: