services:
  redis:
    image: redis:8.2-alpine
    container_name: redis_bd
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      depends_on:
        redis:
          condition: service_healthy
      restart: always
      ports:
        - 5000:5000



volumes:
  redis_data:

