services:
  mariadb:
    image: mariadb:latest # Or a specific version like mariadb:10.8
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: your_root_password # Change this to a strong password
      MARIADB_DATABASE: your_database_name
      MARIADB_USER: your_user
      MARIADB_PASSWORD: your_password
    volumes:
      - mariadb_data:/var/lib/mysql # Persistent storage for data
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    restart: unless-stopped

volumes:
  mariadb_data:   