services:
  mariadb:
    image: mariadb:10.9
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: mybd
      MARIADB_USER: olred
      MARIADB_PASSWORD: user_password

    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      depends_on:
        - mariadb
      restart: always

volumes:
  mariadb_data:


