services:
  mariadb:
    image: mariadb:10.9
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: mybd
      MARIADB_USER: olred
      MARIADB_PASSWORD: user_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "olred", "-puser_password"]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - mariadb_data:/var/lib/mysql
    #ports:
    #  - 3306:3306
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
    image: nginx:latest
    # ports:
    #  - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      depends_on:
        mariadb:
          condition: service_healthy
      restart: always
      ports:
        - 3000:3000

volumes:
  mariadb_data:


