services:
  mariadb:
    image: mariadb:10.8 # Or a specific version like mariadb:10.8
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}" 
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}" 
    volumes:
      - mariadb_data:/var/lib/mysql 
    #ports:
    #  - 3306:3306 
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mariadb", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
  

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app    
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  app:
    build:
      context: .   
      dockerfile: Dockerfile 
    env_file:
      - ./.env
    depends_on: 
      mariadb:
        condition: service_healthy
    restart: always 


volumes:
  mariadb_data:  
