services:
  # Контейнер с Node.js и app
  app:
    build:
      context: ./nodejs-app_01    
    # working_dir: /opt/server
    #volumes:
    #  - ./app:/opt/server
    #  - ./static:/opt/static
    ports:
      - '3000:3000'
    depends_on:
      memcached:
        condition: service_healthy
    restart: always    

  # Контейнер с базой данных
  memcached:
    image: memcached:1.6-alpine
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'echo stats | nc localhost 11211 > /dev/null'"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always 

  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app    
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

 
