services:
  database:
    image: postgres:17
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
          POSTGRES_USER: "${POSTGRES_USER}"
          POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
          POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: ./golang-app_01
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./golang-app_01/.env
    restart: always
    depends_on:
      database:
        condition: service_healthy

volumes:
  pg_data: